---
title: "Logue Lab - Song Matching Experiment - Data Handling and Analysis"
output:   
  html_document:
    keep_md: true
    theme: journal
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    code_folding: hide
---

```{r Loading Libraries, message= FALSE, warning = FALSE}
library(lme4)
library(plyr)
library(ggplot2)
library(afex)
library(emmeans)
library(ggthemes)
library(tidyverse)
library(kableExtra)
library(Hmisc)
library(binom)
library(Rmisc)
library(magick)
library(webshot)
library(magrittr)
library(multcomp)
library(data.table)
library(here)
library(sound)
library(audio)
library(seewave)
library(phonTools)
library(tuneR)

theme_alan <- function(base_size = 12 , base_family = "")
{
  half_line <- base_size/2
  colors <- ggthemes_data$few
  gray <- colors$medium["gray"]
  black <- colors$dark["black"]
  
  theme(
    line = element_line(colour = "black", size = 0.5, linetype = 1, lineend = "butt"),
    rect = element_rect(fill = "white", 
                        colour = "black", size = 0.5, linetype = 1),
    text = element_text(family = base_family, face = "plain", colour = "black", 
                        size = base_size, lineheight = 0.9, hjust = 0.5, vjust = 0.5,
                        angle = 0, margin = margin(), debug = FALSE),
    
    axis.line = element_blank(),
    axis.line.x = NULL,
    axis.line.y = NULL, 
    axis.text = element_text(size = rel(0.8), colour = "grey30"),
    axis.text.x = element_text(margin = margin(t = 0.8 * half_line/2), vjust = 1),
    axis.text.x.top = element_text(margin = margin(b = 0.8 * half_line/2), vjust = 0),
    axis.text.y = element_text(margin = margin(r = 0.8 * half_line/2), hjust = 1),
    axis.text.y.right = element_text(margin = margin(l = 0.8 * half_line/2), hjust = 0), 
    axis.ticks = element_line(colour = "grey20"), 
    axis.ticks.length = unit(half_line/2, "pt"),
    axis.title.x = element_text(margin = margin(t = half_line), vjust = 1),
    axis.title.x.top = element_text(margin = margin(b = half_line), vjust = 0),
    axis.title.y = element_text(angle = 90, margin = margin(r = half_line), vjust = 1),
    axis.title.y.right = element_text(angle = -90, margin = margin(l = half_line), vjust = 0),
    
    legend.background = element_rect(colour = NA),
    legend.spacing = unit(0.4, "cm"), 
    legend.spacing.x = NULL, 
    legend.spacing.y = NULL,
    legend.margin = margin(0.2, 0.2, 0.2, 0.2, "cm"),
    legend.key = element_rect(fill = "white", colour = NA), 
    legend.key.size = unit(1.2, "lines"), 
    legend.key.height = NULL,
    legend.key.width = NULL,
    legend.text = element_text(size = rel(0.8)), 
    legend.text.align = NULL,
    legend.title = element_text(hjust = 0),
    legend.title.align = NULL,
    legend.position = "right", 
    legend.direction = NULL,
    legend.justification = "center", 
    legend.box = NULL,
    legend.box.margin = margin(0, 0, 0, 0, "cm"),
    legend.box.background = element_blank(),
    legend.box.spacing = unit(0.4, "cm"),
    
    panel.background = element_rect(fill = "white", colour = NA),
    panel.border = element_rect(fill = NA, colour = "grey20"),
    panel.grid.major = element_line(colour = "grey92"),
    panel.grid.minor = element_line(colour = "grey92", size = 0.25),
    panel.spacing = unit(half_line, "pt"),
    panel.spacing.x = NULL,
    panel.spacing.y = NULL,
    panel.ontop = FALSE,
    
    strip.background = element_rect(fill = "NA", colour = "NA"),
    strip.text = element_text(colour = "grey10", size = rel(0.8)),
    strip.text.x = element_text(margin = margin(t = half_line, b = half_line)),
    strip.text.y = element_text(angle = 0, margin = margin(l = half_line, r = half_line)),
    strip.placement = "inside",
    strip.placement.x = NULL, 
    strip.placement.y = NULL,
    strip.switch.pad.grid = unit(0.1, "cm"), 
    strip.switch.pad.wrap = unit(0.1, "cm"), 
    
    plot.background = element_rect(colour = "white"),
    plot.title = element_text(size = rel(1.2), hjust = 0, vjust = 1, margin = margin(b = half_line * 1.2)),
    plot.subtitle = element_text(size = rel(0.9), hjust = 0, vjust = 1, margin = margin(b = half_line * 0.9)),
    plot.caption = element_text(size = rel(0.9), hjust = 1, vjust = 1, margin = margin(t = half_line * 0.9)), 
    plot.margin = margin(half_line, half_line, half_line, half_line),
    
    complete = TRUE)
}


```

```{r Creating Stimuli - Concatenating our files, message= FALSE, warning = FALSE, results = "hide"}
#DAWN

DawnSongsList <- read.csv(here("/Simulated/Single/Stimlists", "DawnStims.csv"))
DawnSongsList$SongPath <- as.factor(DawnSongsList$SongPath)
                               
DawnSongsTrack <- appendSample(DawnSongsList$SongPath[1],DawnSongsList$SongPath[2], DawnSongsList$SongPath[3],
                      DawnSongsList$SongPath[4],DawnSongsList$SongPath[5],DawnSongsList$SongPath[6],
                      DawnSongsList$SongPath[7],DawnSongsList$SongPath[8],DawnSongsList$SongPath[9],
                      DawnSongsList$SongPath[10],DawnSongsList$SongPath[11],DawnSongsList$SongPath[12],
                      DawnSongsList$SongPath[13],DawnSongsList$SongPath[14],DawnSongsList$SongPath[15],
                      DawnSongsList$SongPath[16],DawnSongsList$SongPath[17],DawnSongsList$SongPath[18],
                      DawnSongsList$SongPath[19],DawnSongsList$SongPath[20],DawnSongsList$SongPath[21],
                      DawnSongsList$SongPath[22],DawnSongsList$SongPath[23],DawnSongsList$SongPath[24],
                      DawnSongsList$SongPath[25],DawnSongsList$SongPath[26],DawnSongsList$SongPath[27],
                      DawnSongsList$SongPath[28],DawnSongsList$SongPath[29],DawnSongsList$SongPath[30])


saveSample(DawnSongsTrack, 
            here("Simulated/Single/Stimuli/Dawn", 
                  paste("Stimtrack-Dawn", ".wav", sep = "")),
           overwrite = TRUE)


#AFTERNOON



```